# Generated by Django 2.2.24 on 2021-11-19 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumb',
            field=models.ImageField(blank=True, default='PiscoSour.png', upload_to=''),
        ),
    ]
